### ISSUE TITLE
Please be consistent with current developing branch( WE ARE IN VERSION2 BRANCH NOW!!!)

### ISSUE THREAD

**Issue by lunjielee** [ShaimaaAliECE/se3350_project-group-15#14]
please, everyone, create your own branch based on the version2 branch, not the other branch, especially not to delete everything from your old branch then copy all files from version2 and then commit and push. If you really want to do this, delete all your commits before copying all files from the version2 branch !!!

I'm not gonna cherry-pick your commits if they can't be merged with the version2 branch

**Comment by HenryCZhang** [comment]
Why does it still show ChenWang is the default branch?

**Comment by lunjielee** [comment]
main branch is version2 now
